apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-graphql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-graphql
  template:
    metadata:
      labels:
        app: k8s-graphql
    spec:
      containers:
      - image: {{IMAGE}}
        imagePullPolicy: Always
        name: k8s-graphql
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-graphql
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
  selector:
    app: k8s-graphql
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-graphql
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/security-groups: sg-0d6314265d6ad7f7c
  labels:
    app: k8s-graphql
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: k8s-graphql
              servicePort: 80
