apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-graphql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-graphql
  template:
    metadata:
      labels:
        app: k8s-graphql
    spec:
      containers:
      - image: {{IMAGE}}
        imagePullPolicy: Always
        name: k8s-graphql
        ports:
        - containerPort: 80